services:
  api:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "8000:8000"
    environment:
      USE_SQLITE: "false"
      DATABASE_URL: postgresql+psycopg://mediacore:mediacore@postgres:5432/mediacore
      REDIS_URL: redis://redis:6379/0
      STORAGE_ROOT: /data/files
      SEED_API_KEY: dev-api-key-change-me
      SYNC_DOWNLOAD: "false"
      EVENTS_REDIS_ENABLED: "false"
      APP_NAME: MediaCore
    volumes:
      - media_data:/data/files
    depends_on:
      - postgres
      - redis

  worker:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    command: ["python", "-m", "dramatiq", "apps.worker.actors", "--processes", "1", "--threads", "4"]
    environment:
      USE_SQLITE: "false"
      DATABASE_URL: postgresql+psycopg://mediacore:mediacore@postgres:5432/mediacore
      REDIS_URL: redis://redis:6379/0
      STORAGE_ROOT: /data/files
      EVENTS_REDIS_ENABLED: "false"
    volumes:
      - media_data:/data/files
    depends_on:
      - postgres
      - redis
      - api

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: mediacore
      POSTGRES_PASSWORD: mediacore
      POSTGRES_DB: mediacore
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/data/postgres

volumes:
  pg_data:
  media_data:
