replicaCount: 1

image:
  repository: mediacore/api
  tag: "0.1.0"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8000

ingress:
  enabled: false
  host: mediacore.local

env:
  USE_SQLITE: "false"
  SYNC_DOWNLOAD: "false"

postgres:
  enabled: true
  database: mediacore
  username: mediacore

redis:
  enabled: true

worker:
  enabled: true
  replicas: 1

resources: {}
